// Centralized HTTP Status Codes
// Similar to FastAPI's status module

// 2xx Success
export const HTTP_200_OK = 200;
export const HTTP_201_CREATED = 201;
export const HTTP_202_ACCEPTED = 202;
export const HTTP_204_NO_CONTENT = 204;

// 3xx Redirection
export const HTTP_301_MOVED_PERMANENTLY = 301;
export const HTTP_302_FOUND = 302;
export const HTTP_304_NOT_MODIFIED = 304;

// 4xx Client Errors
export const HTTP_400_BAD_REQUEST = 400;
export const HTTP_401_UNAUTHORIZED = 401;
export const HTTP_403_FORBIDDEN = 403;
export const HTTP_404_NOT_FOUND = 404;
export const HTTP_405_METHOD_NOT_ALLOWED = 405;
export const HTTP_409_CONFLICT = 409;
export const HTTP_422_UNPROCESSABLE_ENTITY = 422;
export const HTTP_429_TOO_MANY_REQUESTS = 429;

// 5xx Server Errors
export const HTTP_500_INTERNAL_SERVER_ERROR = 500;
export const HTTP_501_NOT_IMPLEMENTED = 501;
export const HTTP_502_BAD_GATEWAY = 502;
export const HTTP_503_SERVICE_UNAVAILABLE = 503;
export const HTTP_504_GATEWAY_TIMEOUT = 504;

// Default export for convenience
export default {
    // 2xx Success
    OK: HTTP_200_OK,
    CREATED: HTTP_201_CREATED,
    ACCEPTED: HTTP_202_ACCEPTED,
    NO_CONTENT: HTTP_204_NO_CONTENT,
    
    // 3xx Redirection
    MOVED_PERMANENTLY: HTTP_301_MOVED_PERMANENTLY,
    FOUND: HTTP_302_FOUND,
    NOT_MODIFIED: HTTP_304_NOT_MODIFIED,
    
    // 4xx Client Errors
    BAD_REQUEST: HTTP_400_BAD_REQUEST,
    UNAUTHORIZED: HTTP_401_UNAUTHORIZED,
    FORBIDDEN: HTTP_403_FORBIDDEN,
    NOT_FOUND: HTTP_404_NOT_FOUND,
    METHOD_NOT_ALLOWED: HTTP_405_METHOD_NOT_ALLOWED,
    CONFLICT: HTTP_409_CONFLICT,
    UNPROCESSABLE_ENTITY: HTTP_422_UNPROCESSABLE_ENTITY,
    TOO_MANY_REQUESTS: HTTP_429_TOO_MANY_REQUESTS,
    
    // 5xx Server Errors
    INTERNAL_SERVER_ERROR: HTTP_500_INTERNAL_SERVER_ERROR,
    NOT_IMPLEMENTED: HTTP_501_NOT_IMPLEMENTED,
    BAD_GATEWAY: HTTP_502_BAD_GATEWAY,
    SERVICE_UNAVAILABLE: HTTP_503_SERVICE_UNAVAILABLE,
    GATEWAY_TIMEOUT: HTTP_504_GATEWAY_TIMEOUT
};
